-- TripMate 신규 기능(채팅/안심신고/마이페이지 프로필/후기 이미지) 반영용 스크립트
-- 원격 MariaDB에 1회 수동 실행 필요 (마이그레이션 툴 미사용)
-- 이미 실행한 경우 다시 실행해도 안전하도록 IF NOT EXISTS 위주로 작성함

-- 1) 채팅방
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_ROOM (
    ROOM_ID      VARCHAR(30)  NOT NULL,
    MOIM_ID      VARCHAR(30)  NULL,
    TITLE        VARCHAR(200) NOT NULL,

    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CREATE_USER  VARCHAR(30)  NOT NULL,
    CREATE_DT    DATETIME     NOT NULL,
    UPDATE_USER  VARCHAR(30)  NULL,
    UPDATE_DT    DATETIME     NULL,

    PRIMARY KEY (ROOM_ID)
);

-- 2) 채팅방 멤버
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_MEMBER (
    ROOM_ID       VARCHAR(30) NOT NULL,
    USER_ID       VARCHAR(30) NOT NULL,
    JOIN_DT       DATETIME    NOT NULL,
    LAST_READ_DT  DATETIME    NULL,

    PRIMARY KEY (ROOM_ID, USER_ID)
);
ALTER TABLE TB_TRMA_CHAT_MEMBER ADD COLUMN IF NOT EXISTS LAST_READ_DT DATETIME NULL;

-- 3) 채팅 메시지
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_MESSAGE (
    MESSAGE_ID   BIGINT AUTO_INCREMENT,
    ROOM_ID      VARCHAR(30)  NOT NULL,
    SENDER_ID    VARCHAR(30)  NOT NULL,
    CONTENT      VARCHAR(1000) NOT NULL,
    CREATE_DT    DATETIME     NOT NULL,

    PRIMARY KEY (MESSAGE_ID),
    KEY IDX_CHAT_MESSAGE_ROOM (ROOM_ID, CREATE_DT)
);

-- 4) 안심신고
CREATE TABLE IF NOT EXISTS TB_TRMA_SAFETY_REPORT (
    REPORT_ID       BIGINT AUTO_INCREMENT,
    MOIM_ID         VARCHAR(30)  NOT NULL,
    TARGET_USER_ID  VARCHAR(30)  NOT NULL,
    REPORT_TYPE_CD  VARCHAR(10)  NOT NULL,
    CONTENT         VARCHAR(1000) NOT NULL,
    STATE_CD        VARCHAR(10)  NOT NULL DEFAULT 'N',

    CREATE_USER     VARCHAR(30)  NOT NULL,
    CREATE_DT       DATETIME     NOT NULL,
    UPDATE_USER     VARCHAR(30)  NULL,
    UPDATE_DT       DATETIME     NULL,

    PRIMARY KEY (REPORT_ID)
);

-- 5) 마이페이지 프로필 확장 컬럼
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS AREA_NM VARCHAR(100) NULL;
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS PROFILE_IMG_URL VARCHAR(300) NULL;

-- 6) 후기 이미지 컬럼(콤마 구분 URL 목록)
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS IMG_URLS VARCHAR(2000) NULL;

-- 7) 관광지 지도 좌표(한국관광공사 detailCommon2의 mapx/mapy)
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS MAP_X DECIMAL(11,7) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS MAP_Y DECIMAL(10,7) NULL;

-- 8) 사용자 구사 언어(마이페이지 "사용 언어" 카드, 최대 3개)
CREATE TABLE IF NOT EXISTS TB_TRMA_USER_LANGUAGE (
    USER_ID      VARCHAR(30) NOT NULL,
    LANG_CD      VARCHAR(10) NOT NULL,
    LEVEL_CD     VARCHAR(10) NOT NULL,
    SORT_ORDER   INT         NOT NULL DEFAULT 0,

    PRIMARY KEY (USER_ID, LANG_CD)
);

-- 9) 알림(모임 신청/채팅/여행 완료)
CREATE TABLE IF NOT EXISTS TB_TRMA_NOTIFICATION (
    NOTI_ID      BIGINT AUTO_INCREMENT,
    USER_ID      VARCHAR(30)  NOT NULL,
    TYPE_CD      VARCHAR(20)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    CONTENT      VARCHAR(500) NULL,
    LINK_URL     VARCHAR(300) NULL,
    IS_READ      CHAR(1)      NOT NULL DEFAULT 'N',
    CREATE_DT    DATETIME     NOT NULL,

    PRIMARY KEY (NOTI_ID),
    KEY IDX_NOTI_USER (USER_ID, CREATE_DT)
);

-- 10) 소모임 대표 사진(생성 마법사 "10-6 CREATE AD PREVIEW" 화면)
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_IMG_URL VARCHAR(300) NULL;

-- 11) 관광지명/개요 번역 캐시(한국관광공사 데이터는 한국어만 제공되므로,
--     최초 조회 시 Gemini로 번역한 결과를 저장해두고 이후에는 재사용한다)
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_NM_EN VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_NM_JA VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_CONTENT_EN TEXT NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_CONTENT_JA TEXT NULL;

-- 12) 관광지 주소 번역 캐시(도로명주소/상세주소, 위 11번과 동일한 이유/방식)
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS ROAD_ADDR_EN VARCHAR(300) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS ROAD_ADDR_JA VARCHAR(300) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS DETAIL_ADDR_EN VARCHAR(300) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS DETAIL_ADDR_JA VARCHAR(300) NULL;

-- 13) 관광지 상세 후기(TB_TRMA_MOIM_REVIEW, REVIEW_TYPE_CD='T')는 특정 모임(여행 일정)에
--     소속되지 않고 관광지 페이지에서 바로 작성되므로 MOIM_ID/MOIM_START_DT/MOIM_END_DT가 없다.
--     기존 스키마는 이 3개 컬럼이 NOT NULL이라 해당 리뷰 등록 INSERT가 실패했으므로 NULL 허용으로 완화한다.
--     (MOIM_ID로 등록되는 모임 후기(REVIEW_TYPE_CD='O')는 계속 값이 채워진다)
ALTER TABLE TB_TRMA_MOIM_REVIEW MODIFY COLUMN MOIM_ID VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_MOIM_REVIEW MODIFY COLUMN MOIM_START_DT DATE NULL;
ALTER TABLE TB_TRMA_MOIM_REVIEW MODIFY COLUMN MOIM_END_DT DATE NULL;

-- 14) 소모임 제목/소개 번역 캐시(사용자가 직접 입력하는 값이라 관광지처럼 한국어만
--     있으므로, 위 11번과 동일한 방식으로 최초 조회 시 Gemini로 번역해 캐시해둔다)
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_TITLE_EN VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_TITLE_JA VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_DSCR_EN TEXT NULL;
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_DSCR_JA TEXT NULL;

-- 15) 채팅방 멤버 참여 상태(정상/추방됨). 모임에서 추방되면 채팅방 멤버 행은 남겨두고
--     이 값만 'K'로 바꿔서, 채팅 목록/방에는 계속 보이되 "추방됨"으로 표시하고 더 이상
--     메시지를 보낼 수 없게 막는다. 스스로 나가는 경우는 행 자체를 삭제한다.
ALTER TABLE TB_TRMA_CHAT_MEMBER ADD COLUMN IF NOT EXISTS STATE_CD VARCHAR(10) NOT NULL DEFAULT 'A';

-- 16) 소모임 대표 이미지(MOIM_IMG_URL)를 첫 일정 관광지 이미지로 자동 채우는 기능을
--     추가했는데, 신규 생성/일정 수정 시점부터만 채워져서 기존에 이미 만들어져 있던
--     소모임들은 여전히 비어 있다. 한 번만 일괄로 채워준다(이후는 애플리케이션이 자동 갱신).
UPDATE TB_TRMA_MOIM_LIST m
SET MOIM_IMG_URL = (
    SELECT t.FIRST_IMAGE
    FROM TB_TRMA_MOIM_CALENDAR c
    LEFT JOIN TB_TRMA_TOUR_LIST t ON c.TOUR_ID = t.TOUR_ID
    WHERE c.MOIM_ID = m.MOIM_ID
    ORDER BY c.START_DT ASC, c.RMKS ASC
    LIMIT 1
)
WHERE m.MOIM_IMG_URL IS NULL;

-- 17) 관광지 검색(tourSearch, 소모임 일정 추가에서 씀) 성능 개선용 인덱스.
--     이 쿼리는 관광지별 평균 평점(TB_TRMA_MOIM_REVIEW)과 카테고리 목록
--     (TB_TRMA_TOUR_CATE)을 TOUR_ID로 GROUP BY 해서 구하는데, TOUR_ID에 인덱스가
--     없으면 검색할 때마다 두 테이블을 통째로 스캔해서 집계해야 해서 데이터가 쌓일수록
--     느려진다. 인덱스를 추가하면 결과는 그대로고 속도만 개선된다.
CREATE INDEX IF NOT EXISTS IDX_MOIM_REVIEW_TOUR_ID ON TB_TRMA_MOIM_REVIEW(TOUR_ID);
CREATE INDEX IF NOT EXISTS IDX_TOUR_CATE_TOUR_ID ON TB_TRMA_TOUR_CATE(TOUR_ID);
CREATE INDEX IF NOT EXISTS IDX_TOUR_LIST_USE_YN ON TB_TRMA_TOUR_LIST(USE_YN);

-- 18) 후기(관광지/소모임) 번역 캐시. 지금까지는 후기가 "계속 새로 쌓이는 데이터"라는
--     이유로 조회할 때마다 매번 Gemini로 다시 번역했는데, 그 결과 AI가 잠깐 끊기면
--     후기 번역이 통째로 안 보였다. 관광지명/모임 제목과 동일한 방식으로 한 번 번역한
--     결과를 여기에 캐시해두고, 이후 조회부터는 캐시를 재사용한다.
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS REVIEW_TITLE_EN VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS REVIEW_TITLE_JA VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS REVIEW_CONTENT_EN TEXT NULL;
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS REVIEW_CONTENT_JA TEXT NULL;

-- 19) 채팅 메시지 번역 캐시. 메시지 전송 시점에 영어/일본어 번역을 한 번만 만들어
--     여기에 저장해두고, 이후 그 메시지를 누가 다시 보든(실시간 수신 포함) 캐시된
--     값을 그대로 쓴다. AI가 전송 당시 끊겨 있었으면 null로 남고, 조회 시 최근
--     메시지 한정으로 재시도해서 채워넣는다.
ALTER TABLE TB_TRMA_CHAT_MESSAGE ADD COLUMN IF NOT EXISTS CONTENT_EN TEXT NULL;
ALTER TABLE TB_TRMA_CHAT_MESSAGE ADD COLUMN IF NOT EXISTS CONTENT_JA TEXT NULL;

-- 20) 관광지 AI 이용정보(운영시간/휴무일/입장료/주차 등) 캐시. 지금까지는 조회할 때마다
--     매번 Gemini를 호출해서 AI가 끊기면 이용정보 자체가 안 보였다. 조회에 성공하면
--     항상 여기에 최신 결과를 저장해두고, 다음에 AI 호출이 실패했을 때는 이 저장된
--     값을 대신 보여준다(언어별로 결과 문장이 다르므로 TOUR_ID+LANG_CD로 구분).
CREATE TABLE IF NOT EXISTS TB_TRMA_TOUR_AI_INFO (
    TOUR_ID               VARCHAR(50)  NOT NULL,
    LANG_CD               VARCHAR(10)  NOT NULL,
    OPERATING_HOURS       VARCHAR(500) NULL,
    CLOSED_DAYS           VARCHAR(500) NULL,
    ADMISSION_FEE_IS_FREE VARCHAR(10)  NULL,
    ADMISSION_FEE_DETAILS VARCHAR(500) NULL,
    WEBSITE_URL           VARCHAR(500) NULL,
    PARKING_AVAILABLE     VARCHAR(10)  NULL,
    PARKING_FEE_INFO      VARCHAR(500) NULL,
    LAST_UPDATED_NOTE     VARCHAR(500) NULL,
    UPDATE_DT             DATETIME     NOT NULL,

    PRIMARY KEY (TOUR_ID, LANG_CD)
);
