-- TripMate 신규 기능(채팅/안심신고/마이페이지 프로필/후기 이미지) 반영용 스크립트
-- 원격 MariaDB에 1회 수동 실행 필요 (마이그레이션 툴 미사용)
-- 이미 실행한 경우 다시 실행해도 안전하도록 IF NOT EXISTS 위주로 작성함

-- 1) 채팅방
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_ROOM (
    ROOM_ID      VARCHAR(30)  NOT NULL,
    MOIM_ID      VARCHAR(30)  NULL,
    TITLE        VARCHAR(200) NOT NULL,

    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CREATE_USER  VARCHAR(30)  NOT NULL,
    CREATE_DT    DATETIME     NOT NULL,
    UPDATE_USER  VARCHAR(30)  NULL,
    UPDATE_DT    DATETIME     NULL,

    PRIMARY KEY (ROOM_ID)
);

-- 2) 채팅방 멤버
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_MEMBER (
    ROOM_ID       VARCHAR(30) NOT NULL,
    USER_ID       VARCHAR(30) NOT NULL,
    JOIN_DT       DATETIME    NOT NULL,
    LAST_READ_DT  DATETIME    NULL,

    PRIMARY KEY (ROOM_ID, USER_ID)
);
ALTER TABLE TB_TRMA_CHAT_MEMBER ADD COLUMN IF NOT EXISTS LAST_READ_DT DATETIME NULL;

-- 3) 채팅 메시지
CREATE TABLE IF NOT EXISTS TB_TRMA_CHAT_MESSAGE (
    MESSAGE_ID   BIGINT AUTO_INCREMENT,
    ROOM_ID      VARCHAR(30)  NOT NULL,
    SENDER_ID    VARCHAR(30)  NOT NULL,
    CONTENT      VARCHAR(1000) NOT NULL,
    CREATE_DT    DATETIME     NOT NULL,

    PRIMARY KEY (MESSAGE_ID),
    KEY IDX_CHAT_MESSAGE_ROOM (ROOM_ID, CREATE_DT)
);

-- 4) 안심신고
CREATE TABLE IF NOT EXISTS TB_TRMA_SAFETY_REPORT (
    REPORT_ID       BIGINT AUTO_INCREMENT,
    MOIM_ID         VARCHAR(30)  NOT NULL,
    TARGET_USER_ID  VARCHAR(30)  NOT NULL,
    REPORT_TYPE_CD  VARCHAR(10)  NOT NULL,
    CONTENT         VARCHAR(1000) NOT NULL,
    STATE_CD        VARCHAR(10)  NOT NULL DEFAULT 'N',

    CREATE_USER     VARCHAR(30)  NOT NULL,
    CREATE_DT       DATETIME     NOT NULL,
    UPDATE_USER     VARCHAR(30)  NULL,
    UPDATE_DT       DATETIME     NULL,

    PRIMARY KEY (REPORT_ID)
);

-- 5) 마이페이지 프로필 확장 컬럼
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS AREA_NM VARCHAR(100) NULL;
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(500) NULL;
ALTER TABLE TB_TRMA_USER_INFO ADD COLUMN IF NOT EXISTS PROFILE_IMG_URL VARCHAR(300) NULL;

-- 6) 후기 이미지 컬럼(콤마 구분 URL 목록)
ALTER TABLE TB_TRMA_MOIM_REVIEW ADD COLUMN IF NOT EXISTS IMG_URLS VARCHAR(2000) NULL;

-- 7) 관광지 지도 좌표(한국관광공사 detailCommon2의 mapx/mapy)
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS MAP_X DECIMAL(11,7) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS MAP_Y DECIMAL(10,7) NULL;

-- 8) 사용자 구사 언어(마이페이지 "사용 언어" 카드, 최대 3개)
CREATE TABLE IF NOT EXISTS TB_TRMA_USER_LANGUAGE (
    USER_ID      VARCHAR(30) NOT NULL,
    LANG_CD      VARCHAR(10) NOT NULL,
    LEVEL_CD     VARCHAR(10) NOT NULL,
    SORT_ORDER   INT         NOT NULL DEFAULT 0,

    PRIMARY KEY (USER_ID, LANG_CD)
);

-- 9) 알림(모임 신청/채팅/여행 완료)
CREATE TABLE IF NOT EXISTS TB_TRMA_NOTIFICATION (
    NOTI_ID      BIGINT AUTO_INCREMENT,
    USER_ID      VARCHAR(30)  NOT NULL,
    TYPE_CD      VARCHAR(20)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    CONTENT      VARCHAR(500) NULL,
    LINK_URL     VARCHAR(300) NULL,
    IS_READ      CHAR(1)      NOT NULL DEFAULT 'N',
    CREATE_DT    DATETIME     NOT NULL,

    PRIMARY KEY (NOTI_ID),
    KEY IDX_NOTI_USER (USER_ID, CREATE_DT)
);

-- 10) 소모임 대표 사진(생성 마법사 "10-6 CREATE AD PREVIEW" 화면)
ALTER TABLE TB_TRMA_MOIM_LIST ADD COLUMN IF NOT EXISTS MOIM_IMG_URL VARCHAR(300) NULL;

-- 11) 관광지명/개요 번역 캐시(한국관광공사 데이터는 한국어만 제공되므로,
--     최초 조회 시 Gemini로 번역한 결과를 저장해두고 이후에는 재사용한다)
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_NM_EN VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_NM_JA VARCHAR(200) NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_CONTENT_EN TEXT NULL;
ALTER TABLE TB_TRMA_TOUR_LIST ADD COLUMN IF NOT EXISTS TOUR_CONTENT_JA TEXT NULL;
