# 애플리케이션 이름
spring.application.name=backend

# 서버 포트
server.port=8080

# MySQL 연결 정보
spring.datasource.url=jdbc:mariadb://34.158.198.178:3306/trma?useSsl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=tmadmin
spring.datasource.password=xmflq00!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.backend.trma.dto

# JPA 설정
spring.jpa.hibernate.ddl-auto=validate

# 실행 SQL 출력
spring.jpa.show-sql=true

# SQL 보기 좋게 출력
spring.jpa.properties.hibernate.format_sql=true

# 개발 편의 옵션
spring.jpa.open-in-view=false

# jjwt
jwt.secret=trma-secret-key-2026-this-key-must-be-long-enough-123456789
jwt.expiration=21600000
jwt.rememberMeExpiration=2592000000
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#gemini
gemini.api.key=AQ.Ab8RN6KPZGOFiD-ARRIi-M5gk2btNE8WPivUi0kDsju48JZi7Q
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

#한국관광공사API
tour.api.host=apis.data.go.kr
# 1. 한국관광공사_기초지자체 중심 관광지 정보
tour.api.areaBasedList.path=/B551011/LocgoHubTarService1/areaBasedList1
tour.api.areaBasedList.key=c5ad607a8d17e7f40352972992f92c3e8a01bff3c1a6744330fffb568f444e60
# 2.한국관광공사_국문 관광정보 서비스_GW
tour.api.KorService.key=c5ad607a8d17e7f40352972992f92c3e8a01bff3c1a6744330fffb568f444e60
# 2-2.공통정보조회
tour.api.KorService.detailCommon.path=B551011/KorService2/detailCommon2
# 2-3-1.지역기반 관광정보조회
tour.api.KorService.areaBasedList.path=B551011/KorService2/areaBasedList2
# 2-3-2.행사 정보 조회
tour.api.KorService.searchFestival.path=B551011/KorService2/searchFestival2
